cbuffer Constants : register(b0)
{
    float2 InverseViewport;

    float  Decay;
    float  Correlation;
    float2 PeakLevels;
    float2 PeakHolds;
    float2 ClipFlags;
    float2 ThresholdData;
    float2 OverThreshold;
    float2 Padding;

    float2 ScopeScale;
    float2 ScopeOffset;
};

Texture2D<float4> SourceTexture : register(t0);
SamplerState SourceSampler : register(s0);

struct FullscreenOutput
{
    float4 position : SV_POSITION;  // Clip-space position of the vertex
    float2 texcoord : TEXCOORD0;    // UV coordinates passed to the pixel shader.
};

// Render a single oversized triangle that covers the entire screen.
// Draw 3 vertices. The vertex shader generates their positions procedurally. The giant triangle covers the entire viewport. The pixel shader runs once for every screen pixel.
// VertexId is automatically generated by Direct3D.
FullscreenOutput MainVS(uint vertexId : SV_VertexID)
{
    FullscreenOutput output;

    if (vertexId == 0)
    {
        // Bottom-left corner
        output.position = float4(-1.0f, -1.0f, 0.0f, 1.0f);
        output.texcoord = float2( 0.0f,  1.0f);
    }
    else
    if (vertexId == 1)
    {
        // Far above the screen
        output.position = float4(-1.0f,  3.0f, 0.0f, 1.0f);
        output.texcoord = float2( 0.0f, -1.0f);
    }
    else
    {
        // Far to the right of the screen.
        output.position = float4(3.0f, -1.0f, 0.0f, 1.0f);
        output.texcoord = float2(2.0f,  1.0f);
    }

    return output;
}

// Fades the previous frame.
float4 FadePS(FullscreenOutput input) : SV_Target0
{
    // Reads the color in the previous texture at the current screen position. Previous is float4(R,G,B,A).
    float4 Previous = SourceTexture.Sample(SourceSampler, input.texcoord); 

    // Use decay to make it darker.
    return Previous * Decay;

//  return float4(Previous.rgb * Decay, Previous.a);
}

float Box(float2 uv, float4 bounds)
{
    float horizontal = step(bounds.x, uv.x) * step(uv.x, bounds.z);
    float vertical = step(bounds.y, uv.y) * step(uv.y, bounds.w);

    return horizontal * vertical;
}

float MarkerMask(float y, float target, float halfWidth)
{
    return step(abs(y - target), halfWidth);
}

float3 DrawPeakColumn(float3 baseColor, float2 uv, float4 bounds, float level, float heldPeak, float clipFlag, float threshold, float overThreshold)
{
    float area       = Box(uv, bounds);
    float width      = bounds.z - bounds.x;
    float height     = bounds.w - bounds.y;
    float localX     = (uv.x - bounds.x) / width;
    float meterValue = 1.0f - ((uv.y - bounds.y) / height);
    float inner      = step(0.10f, localX) * step(localX, 0.90f) * area;

    float fill       = step(meterValue, level) * inner;
    float greenMix   = smoothstep(0.70f, 0.90f, meterValue);
    float redMix     = smoothstep(0.90f, 1.00f, meterValue);

    float3 meterColor = lerp(float3(0.05f, 0.95f, 0.22f), float3(1.00f, 0.78f, 0.05f), greenMix);

    meterColor = lerp(meterColor, float3(1.00f, 0.05f, 0.02f), redMix);
    baseColor  = max(baseColor, meterColor * fill * 0.85f);

    float holdMarker = MarkerMask(meterValue, heldPeak, 0.008f) * inner;

    baseColor = max(baseColor, float3(1.0f, 1.0f, 1.0f) * holdMarker);

    float thresholdMarker = MarkerMask(meterValue, threshold, 0.006f) * inner;
    float3 normalThreshold = float3(1.0f, 0.55f, 0.04f);
    float3 exceededThreshold = float3(1.0f, 0.08f, 0.02f);
    float3 thresholdColor = lerp(normalThreshold, exceededThreshold, saturate(overThreshold));

    baseColor = max(baseColor, thresholdColor * thresholdMarker);

    float clipBand = step(0.965f, meterValue) * step(meterValue, 0.995f) * inner;

    baseColor = max(baseColor, float3(1.0f, 0.02f, 0.01f) * clipBand * saturate(clipFlag));

    float leftBorder = step(localX, 0.015f) * area;
    float rightBorder = step(0.985f, localX) * area;

    baseColor = max(baseColor, float3(0.08f, 0.08f, 0.08f) * (leftBorder + rightBorder));

    return baseColor;
}

float4 PresentPS(FullscreenOutput input) : SV_Target0
{
    float3 hdr    = SourceTexture.Sample(SourceSampler, input.texcoord).rgb;
    float3 mapped = 1.0f - exp(-hdr * 2.2f);
    float3 gamma  = float3(0.45454545f, 0.45454545f, 0.45454545f);
    float3 color  = pow(saturate(mapped), gamma);

    // Draw the guides. The plot occupies the square left of the peak meters. Vertical axis is Mid (L+R). Horizontal axis is Side (L-R).
    const float2 scopeCenter = float2(0.465f, 0.475f);
    const float  scopeRadius = 0.420f;

    float2 scopeDelta     = input.texcoord - scopeCenter;
    float verticalAxis    = step(abs(scopeDelta.x), 0.0015f) * step(abs(scopeDelta.y), scopeRadius);
    float horizontalAxis  = step(abs(scopeDelta.y), 0.0015f) * step(abs(scopeDelta.x), scopeRadius);
    float diamondDistance = abs(scopeDelta.x) + abs(scopeDelta.y);
    float diamondGuide = step(abs(diamondDistance - scopeRadius), 0.0018f);
    float guideMask = saturate(verticalAxis + horizontalAxis + diamondGuide);

    color = max(color, float3(0.16f, 0.18f, 0.20f) * guideMask);

    // Brighter center marker.
    float centerDistance = length(scopeDelta);
    float centerMarker = step(centerDistance, 0.0045f);

    color = max(color, float3(0.34f, 0.37f, 0.40f) * centerMarker);

    // Correlation meter occupies x=0.02..0.90, y=0.925..0.975.
    float4 correlationBounds = float4(0.02f, 0.925f, 0.90f, 0.975f);
    float correlationArea = Box(input.texcoord, correlationBounds);
    float correlationX = ((input.texcoord.x - correlationBounds.x) / (correlationBounds.z - correlationBounds.x)) * 2.0f - 1.0f;
    float negativeFill = step(Correlation, correlationX) * step(correlationX, 0.0f);
    float positiveFill = step(0.0f, correlationX) * step(correlationX, Correlation);

    color = max(color, float3(1.0f, 0.08f, 0.03f) * negativeFill * correlationArea * 0.90f);
    color = max(color, float3(0.05f, 1.0f, 0.25f) * positiveFill * correlationArea * 0.90f);

    float zeroMarker = step(abs(correlationX), 0.006f) * correlationArea;

    color = max(color, float3(0.35f, 0.35f, 0.35f) * zeroMarker);

    // Use separate explicit calls for left and right channels. This avoids dynamic indexing and conditional channel selection in older FXC versions.
    color = DrawPeakColumn(color, input.texcoord, float4(0.930f, 0.080f, 0.956f, 0.880f), PeakLevels.x, PeakHolds.x, ClipFlags.x, ThresholdData.x, OverThreshold.x);
    color = DrawPeakColumn(color, input.texcoord, float4(0.959f, 0.080f, 0.985f, 0.880f), PeakLevels.y, PeakHolds.y, ClipFlags.y, ThresholdData.y, OverThreshold.y);

    return float4(color, 1.0f);
}
